import { FormFieldConfig, DemoPreset, CompanyFeatures } from "./types";

export const FORM_FIELDS: Record<keyof CompanyFeatures, FormFieldConfig> = {
  "Borrowing dependency": {
    label: "Borrowing Dependency",
    category: "solvency",
    description: "Ratio of high-cost loans to total capital & operational revenue. High values indicate severe leverage.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.37,
    unit: "ratio",
    healthy_direction: "lower",
  },
  "Total debt/Total net worth": {
    label: "Total Debt to Net Worth",
    category: "solvency",
    description: "Total liabilities relative to net equity (gearing ratio). Measures leverage cushion.",
    min: 0.0,
    max: 5.0,
    step: 0.01,
    default_median: 0.01,
    unit: "ratio",
    healthy_direction: "lower",
  },
  "Retained Earnings to Total Assets": {
    label: "Retained Earnings to Assets",
    category: "solvency",
    description: "Accumulated retained internal profits / Total Assets. Safety buffer to absorb operational shocks.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.94,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Debt ratio %": {
    label: "Debt Ratio %",
    category: "solvency",
    description: "Total Liabilities / Total Assets. Direct proportion of balance sheet funded by creditors.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.11,
    unit: "%",
    healthy_direction: "lower",
  },
  "Net worth/Assets": {
    label: "Net Worth to Assets",
    category: "solvency",
    description: "Total Net Equity / Total Assets. Measures resilience against asset value write-downs.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.89,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Continuous interest rate (after tax)": {
    label: "After-Tax Interest Coverage",
    category: "solvency",
    description: "Effective continuous interest rate sustainability after corporate tax deductions.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.78,
    unit: "index",
    healthy_direction: "higher",
  },
  "Persistent EPS in the Last Four Seasons": {
    label: "Persistent EPS (4 Quarters)",
    category: "operations",
    description: "Trailing earnings stability across 4 consecutive quarters. Measures revenue reliability.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.22,
    unit: "index",
    healthy_direction: "higher",
  },
  "Net Income to Total Assets": {
    label: "Net Income to Assets (ROA)",
    category: "operations",
    description: "Return on Assets (ROA). Core measure of operational capital efficiency and asset productivity.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.81,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Net profit before tax/Paid-in capital": {
    label: "Pre-Tax Profit / Paid-in Capital",
    category: "operations",
    description: "Pre-tax profitability generated relative to the original shareholder paid-in capital base.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.18,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "After-tax net Interest Rate": {
    label: "Net Interest Margin Efficiency",
    category: "operations",
    description: "Net interest income margin efficiency after tax accounting.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.81,
    unit: "index",
    healthy_direction: "higher",
  },
};

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: "high-risk",
    name: "Acute Distress Profile",
    tagline: "Severe leverage, collapsing EPS, thin equity buffer",
    risk_tier: "High Risk",
    badge_color: "rose",
    description: "Validated high-risk row (prob 1.00): borrowing 0.73, debt ratio 0.29, EPS 0.10, ROA 0.61 — classic pre-distress pattern (exact 4-decimal values from training row 1865).",
    features: {
      "Borrowing dependency": 0.7346,
      "Total debt/Total net worth": 0.5087,
      "Persistent EPS in the Last Four Seasons": 0.1018,
      "Net Income to Total Assets": 0.6059,
      "Retained Earnings to Total Assets": 0.8713,
      "Continuous interest rate (after tax)": 0.7808,
      "Debt ratio %": 0.2926,
      "Net worth/Assets": 0.7074,
      "Net profit before tax/Paid-in capital": 0.0799,
      "After-tax net Interest Rate": 0.8086,
    },
  },
  {
    id: "moderate-risk",
    name: "Marginal Solvency Profile",
    tagline: "Borderline leverage with compressed margins",
    risk_tier: "Medium Risk",
    badge_color: "amber",
    description: "Calibrated moderate row (prob 0.45): borrowing 0.39, debt ratio 0.19, EPS 0.20 — sits at the model's decision boundary.",
    features: {
      "Borrowing dependency": 0.39,
      "Total debt/Total net worth": 0.02,
      "Persistent EPS in the Last Four Seasons": 0.20,
      "Net Income to Total Assets": 0.78,
      "Retained Earnings to Total Assets": 0.92,
      "Continuous interest rate (after tax)": 0.78,
      "Debt ratio %": 0.19,
      "Net worth/Assets": 0.81,
      "Net profit before tax/Paid-in capital": 0.16,
      "After-tax net Interest Rate": 0.81,
    },
  },
  {
    id: "low-risk",
    name: "Resilient Corporate Profile",
    tagline: "Strong equity cushion, high ROA, self-funded growth",
    risk_tier: "Low Risk",
    badge_color: "emerald",
    description: "Validated low-risk row (prob 0.06): minimal borrowing (0.12), debt ratio 0.08, EPS 0.35, ROA 0.88 — prime investment-grade stability.",
    features: {
      "Borrowing dependency": 0.12,
      "Total debt/Total net worth": 0.01,
      "Persistent EPS in the Last Four Seasons": 0.35,
      "Net Income to Total Assets": 0.88,
      "Retained Earnings to Total Assets": 0.95,
      "Continuous interest rate (after tax)": 0.85,
      "Debt ratio %": 0.08,
      "Net worth/Assets": 0.92,
      "Net profit before tax/Paid-in capital": 0.24,
      "After-tax net Interest Rate": 0.86,
    },
  },
];
