import { FormFieldConfig, DemoPreset, CompanyFeatures } from "./types";

export const FORM_FIELDS: Record<keyof CompanyFeatures, FormFieldConfig> = {
  "Borrowing dependency": {
    label: "Loan Reliance",
    category: "solvency",
    description: "How much the company depends on borrowed money. Higher = more risky.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.37,
    unit: "ratio",
    healthy_direction: "lower",
  },
  "Total debt/Total net worth": {
    label: "Debt vs. Own Money",
    category: "solvency",
    description: "For every ₹1 the company owns, how much does it owe? Higher = more danger.",
    min: 0.0,
    max: 5.0,
    step: 0.01,
    default_median: 0.01,
    unit: "ratio",
    healthy_direction: "lower",
  },
  "Retained Earnings to Total Assets": {
    label: "Savings Buffer",
    category: "solvency",
    description: "Rainy-day savings stored inside the company. Higher = safer.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.94,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Debt ratio %": {
    label: "Total Debt Load",
    category: "solvency",
    description: "What percentage of everything the company has is actually debt? Lower = healthier.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.11,
    unit: "%",
    healthy_direction: "lower",
  },
  "Net worth/Assets": {
    label: "Ownership Strength",
    category: "solvency",
    description: "How much of the company is truly owned vs. owed. Higher = stronger.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.89,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Continuous interest rate (after tax)": {
    label: "Interest Payment Capacity",
    category: "solvency",
    description: "Can the company comfortably pay its loan interest? Higher = yes.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.78,
    unit: "index",
    healthy_direction: "higher",
  },
  "Persistent EPS in the Last Four Seasons": {
    label: "Earnings Consistency",
    category: "operations",
    description: "Are profits steady every quarter, or up-and-down? Higher = more stable.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.22,
    unit: "index",
    healthy_direction: "higher",
  },
  "Net Income to Total Assets": {
    label: "Asset Productivity (ROA)",
    category: "operations",
    description: "How much profit is generated from every ₹1 of assets? Higher = better.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.81,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "Net profit before tax/Paid-in capital": {
    label: "Return on Investment",
    category: "operations",
    description: "For every ₹1 investors put in, how much profit before tax? Higher = better.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.18,
    unit: "ratio",
    healthy_direction: "higher",
  },
  "After-tax net Interest Rate": {
    label: "Net Interest Efficiency",
    category: "operations",
    description: "How efficiently the company manages interest income vs. expenses. Higher = better.",
    min: 0.0,
    max: 1.0,
    step: 0.01,
    default_median: 0.81,
    unit: "index",
    healthy_direction: "higher",
  },
};

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: "high-risk",
    name: "🚨 Struggling Startup in Debt",
    tagline: "Heavy loans, weak profits, running out of cash — classic danger signs",
    risk_tier: "High Risk",
    badge_color: "rose",
    description: "A company drowning in debt with inconsistent earnings. The AI flags this as a high-risk profile based on patterns from 6,819 real companies.",
    features: {
      "Borrowing dependency": 0.7346,
      "Total debt/Total net worth": 0.5087,
      "Persistent EPS in the Last Four Seasons": 0.1018,
      "Net Income to Total Assets": 0.6059,
      "Retained Earnings to Total Assets": 0.8713,
      "Continuous interest rate (after tax)": 0.7808,
      "Debt ratio %": 0.2926,
      "Net worth/Assets": 0.7074,
      "Net profit before tax/Paid-in capital": 0.0799,
      "After-tax net Interest Rate": 0.8086,
    },
  },
  {
    id: "moderate-risk",
    name: "🟡 Traditional Manufacturer",
    tagline: "Moderate debt, average profits — sitting on the fence between safe and risky",
    risk_tier: "Medium Risk",
    badge_color: "amber",
    description: "A company with some debt and decent but not great profits. The AI sees warning signs but also some strengths.",
    features: {
      "Borrowing dependency": 0.39,
      "Total debt/Total net worth": 0.02,
      "Persistent EPS in the Last Four Seasons": 0.20,
      "Net Income to Total Assets": 0.78,
      "Retained Earnings to Total Assets": 0.92,
      "Continuous interest rate (after tax)": 0.78,
      "Debt ratio %": 0.19,
      "Net worth/Assets": 0.81,
      "Net profit before tax/Paid-in capital": 0.16,
      "After-tax net Interest Rate": 0.81,
    },
  },
  {
    id: "low-risk",
    name: "🟢 Profitable Tech Giant",
    tagline: "Minimal debt, strong savings, consistent profits — textbook healthy company",
    risk_tier: "Low Risk",
    badge_color: "emerald",
    description: "A company with very little debt, strong savings, and steady profits. The AI identifies this as a low-risk, investment-grade profile.",
    features: {
      "Borrowing dependency": 0.12,
      "Total debt/Total net worth": 0.01,
      "Persistent EPS in the Last Four Seasons": 0.35,
      "Net Income to Total Assets": 0.88,
      "Retained Earnings to Total Assets": 0.95,
      "Continuous interest rate (after tax)": 0.85,
      "Debt ratio %": 0.08,
      "Net worth/Assets": 0.92,
      "Net profit before tax/Paid-in capital": 0.24,
      "After-tax net Interest Rate": 0.86,
    },
  },
];
